%test on the reconstruction under noise and various sampling masks
%Figure 12 of the paper
%this script is for phantom data, with simulated coil sensitivity maps and noise.
%First generate the k-space data and noise using Simulations/Exp3_generate_phantom_data.m, then run this script to perform reconstructions and generate the results.
%After running this code, the reconstruction will be saved to 
%/output/phantom/phantom_recon.mat

% Set project root as the parent folder of this script's folder
this_file = mfilename('fullpath');
[this_dir, ~, ~] = fileparts(this_file);
project_root = fileparts(this_dir);

addpath(project_root);
addpath(fullfile(project_root, 'src'));
addpath(genpath(fullfile(project_root, 'external')));

data_dir = fullfile(project_root, 'data');
output_dir = fullfile(project_root, 'output');

% Load experiment parameters
model_violation = true; %allow model violation (due to coil only approximated by Bh)

%load the phantom image and simulated coils
%data generation is in data/phantom/data_generator.m
im = load(fullfile(data_dir, 'phantom', 'phantom.mat'));
im = im.im;
coil = load(fullfile(data_dir, 'phantom', 'coil_v2.mat')); %coils generated by boit law
sensitivity = coil.sensitivity;
M = coil.M;
h = coil.h;
opt = load(fullfile(data_dir, 'phantom', 'opts.mat'));

%load full k-space
%run data/phantom/data_generator.m
k_data =load(fullfile(data_dir, 'phantom', 'slice_full_v2.mat'));
slice_full = k_data.slice_full;
noise = k_data.noise;

%load sampling pattern
pat = load(fullfile(data_dir, 'phantom', 'pat.mat'));

%Undersampling patterns to loop through.Using BART’s Poisson mask.
%To generate masks, a simple demo to use BART can be found in : /exp/exp2_NLINV_phantom.ipynb
pattern_name = {'pat_3','pat_4','pat_5','pat_10','pat_15','pat_20'};
patterns = {pat.pat_3, pat.pat_4, pat.pat_5,pat.pat_10,pat.pat_15,pat.pat_20};
Rec_l12 = struct(); % Initialize an empty structure
results = cell(1, length(patterns));

% Loop through each pattern
for j = 1:length(patterns)
    sprintf('at pattern %d',j)
    pat = patterns{j};

    Out_best =  lsense(im,h,M,opt.opts,opt.coil_opts,model_violation,sensitivity,pat,noise,true);

    % Update the corresponding slice
    results{j} = Out_best;  % Store result for each pattern
end

% After the parfor loop, assign results to the structure
for j = 1:length(patterns)
    fieldName = sprintf('Out_best_%s', pattern_name{j}); % Create field names
    Rec_l12.(fieldName) = results{j};  % Assign the result to the corresponding field
end

%save(fullfile(output_dir, 'phantom', 'phantom_recon.mat'), "Rec_l12")
